#!/bin/sh

# This script compiles/installs MCS from scratch skiping long
# OAM initialization step that is usually unnecessary for
# development. 
# The script presumes that server's source code is one directory
# above the MCS engine source.
# This script also presumes default installation path for MCS 
# and uses a number of external scripts to start/stop MCS

BUILD_TYPE=debug
MCS_SOURCE_PATH=/git/mariadb-columnstore-server/d1-mariadb-columnstore-engine
MCS_INSTALL_PREFIX=/usr/local/mariadb
MCS_INSTALL_PATH=$MCS_INSTALL_PREFIX/columnstore
MCS_TMP_DIR=/tmp/columnstore_tmp_files
MCS_SCRIPTS_REPO_PREFIX=/git/cs-docker-tools
CPUS=$(getconf _NPROCESSORS_ONLN)

# script
$MCS_SCRIPTS_REPO_PREFIX/shells/stopcs
rm -rf $MCS_INSTALL_PREFIX
rm -rf $MCS_TMP_DIR/*

cd $MCS_SOURCE_PATH
# The magic flag
export SKIP_OAM_INIT=1
cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE && make install -j $CPUS && cd .. && make install -j $CPUS
cp $MCS_SCRIPTS_REPO_PREFIX/columnar/Columnstore.xml $MCS_INSTALL_PATH/etc/

$MCS_INSTALL_PATH/bin/post-mysqld-install
# Wait until mysqld finishes
sleep 3
$MCS_INSTALL_PATH/bin/post-mysql-install
$MCS_INSTALL_PATH/bin/post-mysqld-install

mkdir $MCS_INSTALL_PATH/data1
mkdir $MCS_INSTALL_PATH/data1/systemFiles
mkdir $MCS_INSTALL_PATH/data1/systemFiles/dbrm

# script
$MCS_SCRIPTS_REPO_PREFIX/shells/startcs

# Populate system catalog with initial data
$MCS_INSTALL_PATH/bin/dbbuilder 7

exit 0 
