#!/bin/sh

# This script allows to fast recompile, reinstall
# and restart  MCS when it was initially compiled 
# with SKIP_OAM_INIT=1
# The script doesn't call cmake so one must run
# it manually

# To choose b/w multiply engine MSC directories
MCS_SC_ID=$1

if [ -z $MCS_SC_ID ]; then
    MCS_SOURCE_PATH=/data/mdb-server/storage/columnstore
else
    MCS_SOURCE_PATH=/git/mariadb-columnstore-server/d${MCS_SC_ID}-mariadb-columnstore-engine
fi

MCS_SCRIPTS_REPO_PREFIX=/data/cs-docker-tools
MCS_INSTALL_PATH=/usr/local/mariadb/columnstore
TMP_PATH=/tmp
CPUS=$(getconf _NPROCESSORS_ONLN)

systemctl stop mariadb-columnstore

# Backup the config file
if [ $MCS_SC_ID -eq 1 -o $MCS_SC_ID -eq 2 ] ; then
    cp $MCS_INSTALL_PATH/etc/Columnstore.xml $TMP_PATH/Columnstore.xml 
else
    cp /etc/columnstore/Columnstore.xml $TMP_PATH/Columnstore.xml
fi

#pushd . 
# Run the next step only of previous was successful
if [ $MCS_SC_ID -eq 1 -o $MCS_SC_ID -eq 2 ] ; then
    cd $MCS_SOURCE_PATH && make -j$CPUS install && cp $TMP_PATH/Columnstore.xml $MCS_INSTALL_PATH/etc/Columnstore.xml
else
    cd $MCS_SOURCE_PATH && make -j$CPUS install && cp $TMP_PATH/Columnstore.xml /etc/columnstore/Columnstore.xml
fi

# Script
systemctl start mariadb-columnstore

#popd
