#!/bin/sh

# This script allows to fast recompile, reinstall
# and restart  MCS when it was initially compiled 
# with SKIP_OAM_INIT=1
# The script doesn't call cmake so one must run
# it manually

SKIP_RESTART=$1

MCS_SOURCE_PATH=/data/mdb-server/storage/columnstore

MCS_SCRIPTS_REPO_PREFIX=/data/cs-docker-tools
MCS_INSTALL_PATH=/usr/local/mariadb/columnstore
TMP_PATH=/tmp
CPUS=$(getconf _NPROCESSORS_ONLN)

if [[ -z "$SKIP_RESTART" ]]; then
    systemctl stop mariadb-columnstore
fi

# Backup the config file
cp /etc/columnstore/Columnstore.xml $TMP_PATH/Columnstore.xml

# Run the next step only of previous was successful
cd $MCS_SOURCE_PATH && make -j$CPUS install && cp $TMP_PATH/Columnstore.xml /etc/columnstore/Columnstore.xml

# Script
if [[ -z "$SKIP_RESTART" ]]; then
    systemctl start mariadb-columnstore
fi
