#!/bin/bash

sudo echo This is dumb.  DMLProc seems to need it.

HOME_=/usr/local

LOG_PREFIX=/var/log/mariadb/columnstore
PREFIX=$HOME_/mariadb/columnstore/bin
#PROGS='load_brm workernode controllernode PrimProc ExeMgr DDLProc'
PROGS='load_brm workernode controllernode PrimProc ExeMgr DMLProc DDLProc'
PROGS+=' WriteEngineServer'

for i in $PROGS ; do
	if [ ! -x $PREFIX/$i ] ; then
		echo $i doesn\'t exist
		exit 1
	fi
done

echo Starting...

sed -i 's@<ModuleIPAddr1-1-3>0.0.0.0</ModuleIPAddr1-1-3>@<ModuleIPAddr1-1-3>127.0.0.1</ModuleIPAddr1-1-3>@' $HOME_/mariadb/columnstore/etc/Columnstore.xml

if [ -f $HOME_/mariadb/columnstore/data1/systemFiles/dbrm/BRM_saves_current ] ; then
       echo loading BRM from $HOME_/mariadb/columnstore/data1/systemFiles/dbrm/`cat $HOME_/mariadb/columnstore/data1/systemFiles/dbrm/BRM_saves_current`
       $PREFIX/load_brm $HOME_/mariadb/columnstore/data1/systemFiles/dbrm/`cat $HOME_/mariadb/columnstore/data1/systemFiles/dbrm/BRM_saves_current`
fi
touch $LOG_PREFIX/workernode.log && chmod 666 $LOG_PREFIX/workernode.log
$PREFIX/workernode DBRM_Worker1 &> $LOG_PREFIX/workernode.log &
#echo workernode PID = $!
touch $LOG_PREFIX/controllernode.log && chmod 666 $LOG_PREFIX/controllernode.log
$PREFIX/controllernode &> $LOG_PREFIX/controllernode.log &
#echo controllernode PID = $!
#sleep 1
touch $LOG_PREFIX/primproc.log && chmod 666 $LOG_PREFIX/primproc.log
$PREFIX/PrimProc &> $LOG_PREFIX/primproc.log &
echo PrimProc PID = $!
sleep 1
touch $LOG_PREFIX/exemgr.log && chmod 666 $LOG_PREFIX/exemgr.log
$PREFIX/ExeMgr &> $LOG_PREFIX/exemgr.log &

# example of enabling profiling and leak detection in jemalloc.  jemalloc
# needs to be built with --enable-prof for this to work
#MALLOC_CONF=prof:true,prof_leak:true,zero:true LD_PRELOAD=$HOME_/lib/libjemalloc.so ExeMgr >& $HOME/exemgr.log &

echo ExeMgr PID = $!
touch $LOG_PREFIX/writeengineserver.log && chmod 666 $LOG_PREFIX/writeengineserver.log
$PREFIX/WriteEngineServer &> $LOG_PREFIX/writeengineserver.log &
echo WriteEngineServer PID = $!
sleep 1
touch $LOG_PREFIX/dmlproc.log && chmod 666 $LOG_PREFIX/dmlproc.log
$PREFIX/DMLProc &> $LOG_PREFIX/dmlproc.log &
echo DMLProc PID = $!
touch $LOG_PREFIX/ddlproc.log && chmod 666 $LOG_PREFIX/ddlproc.log
$PREFIX/DDLProc &> $LOG_PREFIX/ddlproc.log &
echo DDLProc PID = $!
#$HOME_/mariadb/columnstore/mysql/bin/mysqld --user=mysql --defaults-file=$HOME_/mariadb/columnstore/mysql/my.cnf > $LOG_PREFIX/mysqld.log &
touch $LOG_PREFIX/mysqld_err.log
chown mysql.mysql $LOG_PREFIX/mysqld_err.log
$HOME_/mariadb/columnstore/mysql//bin/mysqld --basedir=/usr/local/mariadb/columnstore/mysql/ --datadir=/usr/local/mariadb/columnstore/mysql/db --plugin-dir=/usr/local/mariadb/columnstore/mysql/lib/plugin --user=mysql --log-error=$LOG_PREFIX/mysqld_err.log --pid-file=/usr/local/mariadb/columnstore/mysql/db/$(hostname).pid --socket=/usr/local/mariadb/columnstore/mysql/lib/mysql/mysql.sock --port=3306 > $LOG_PREFIX/mysqld.log &
sleep 1

exit 0
