#!/bin/bash

# This script allows to gracefully start MCS
# when it was initially compiled with SKIP_OAM_INIT=1

#sudo echo This is dumb.  DMLProc seems to need it.

MINOR=$1

MCS_INSTALL_PREFIX=/usr/local

LOG_SUBPREFIX=/var/log/mariadb
LOG_PREFIX=$LOG_SUBPREFIX/columnstore
if [ $MINOR -eq 4 ]; then
    MCS_INSTALL_PATH=/var/lib/columnstore
    MCS_INSTALL_BIN=/usr/bin
else
    MCS_INSTALL_PATH=$MCS_INSTALL_PREFIX/mariadb/columnstore
    MCS_INSTALL_BIN=$MCS_INSTALL_PATH/bin
fi
PROGS='load_brm workernode controllernode PrimProc ExeMgr DMLProc DDLProc'
PROGS+=' WriteEngineServer'

for i in $PROGS ; do
	if [ ! -x $MCS_INSTALL_BIN/$i ] ; then
		echo $i doesn\'t exist
		exit 1
	fi
done

echo Starting...

# Ugly hack
#sed -i 's@<ModuleIPAddr1-1-3>0.0.0.0</ModuleIPAddr1-1-3>@<ModuleIPAddr1-1-3>127.0.0.1</ModuleIPAddr1-1-3>@' /etc/columnstore/Columnstore.xml
#sed -i 's@<ModuleIPAddr1-1-3>0.0.0.0</ModuleIPAddr1-1-3>@<ModuleIPAddr1-1-3>127.0.0.1</ModuleIPAddr1-1-3>@' $MCS_INSTALL_PATH/etc/Columnstore.xml

mkdir /var/run/mysqld/
chown -R mysql.mysql /var/run/mysqld

if [ ! -d $LOG_SUBPREFIX ]; then
    mkdir $LOG_SUBPREFIX
fi

if [ ! -d $LOG_PREFIX ]; then
    mkdir $LOG_PREFIX
fi

if [ ! -d /tmp/columnstore_tmp_files ]; then
    mkdir /tmp/columnstore_tmp_files
fi

if [ -f $MCS_INSTALL_PATH/data1/systemFiles/dbrm/BRM_saves_current ] ; then
       echo loading BRM from $MCS_INSTALL_PATH/data1/systemFiles/dbrm/`cat $MCS_INSTALL_PATH/data1/systemFiles/dbrm/BRM_saves_current`
       $MCS_INSTALL_BIN/load_brm $MCS_INSTALL_PATH/data1/systemFiles/dbrm/`cat $MCS_INSTALL_PATH/data1/systemFiles/dbrm/BRM_saves_current`
fi
touch $LOG_PREFIX/workernode.log && chmod 666 $LOG_PREFIX/workernode.log
$MCS_INSTALL_BIN/workernode DBRM_Worker1 &> $LOG_PREFIX/workernode.log &
echo workernode PID = $!
touch $LOG_PREFIX/controllernode.log && chmod 666 $LOG_PREFIX/controllernode.log
$MCS_INSTALL_BIN/controllernode &> $LOG_PREFIX/controllernode.log &
echo controllernode PID = $!
#sleep 1
touch $LOG_PREFIX/primproc.log && chmod 666 $LOG_PREFIX/primproc.log
$MCS_INSTALL_BIN/PrimProc &> $LOG_PREFIX/primproc.log &
echo PrimProc PID = $!
sleep 1
touch $LOG_PREFIX/exemgr.log && chmod 666 $LOG_PREFIX/exemgr.log
#$MCS_INSTALL_BIN/ExeMgr &> $LOG_PREFIX/exemgr.log &
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 $MCS_INSTALL_BIN/ExeMgr -ddd &> $LOG_PREFIX/exemgr.log &
#heaptrack $MCS_INSTALL_BIN/ExeMgr &> $LOG_PREFIX/exemgr.log &
#valgrind --leak-check=full --xtree-memory=full --log-fd=9 9>$LOG_PREFIX/valgrind.log $MCS_INSTALL_BIN/ExeMgr &> $LOG_PREFIX/exemgr.log &

# example of enabling profiling and leak detection in jemalloc.  jemalloc
# needs to be built with --enable-prof for this to work
#MALLOC_CONF=prof:true,prof_leak:true,zero:true LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 ExeMgr >& $HOME/exemgr.log &

echo ExeMgr PID = $!
touch $LOG_PREFIX/writeengineserver.log && chmod 666 $LOG_PREFIX/writeengineserver.log
#heaptrack $MCS_INSTALL_BIN/WriteEngineServer &> $LOG_PREFIX/writeengineserver.log &
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 $MCS_INSTALL_BIN/WriteEngineServer &> $LOG_PREFIX/writeengineserver.log &
echo WriteEngineServer PID = $!
sleep 3
touch $LOG_PREFIX/dmlproc.log && chmod 666 $LOG_PREFIX/dmlproc.log
$MCS_INSTALL_BIN/DMLProc &> $LOG_PREFIX/dmlproc.log &
echo DMLProc PID = $!
touch $LOG_PREFIX/ddlproc.log && chmod 666 $LOG_PREFIX/ddlproc.log
$MCS_INSTALL_BIN/DDLProc &> $LOG_PREFIX/ddlproc.log &
echo DDLProc PID = $!
#$MCS_INSTALL_PATH/mysql/bin/mysqld --user=mysql --defaults-file=$MCS_INSTALL_PATH/mariadb/columnstore/mysql/my.cnf > $LOG_PREFIX/mysqld.log &
touch $LOG_PREFIX/mysqld_err.log
chown mysql.mysql $LOG_PREFIX/mysqld_err.log
if [ -x $MCS_INSTALL_PATH/mysql/bin/mysqld ]; then
    $MCS_INSTALL_PATH/mysql/bin/mysqld --defaults-extra-file=/etc/my.cnf.d/columnstore.cnf --basedir=/usr/local/mariadb/columnstore/mysql/  --datadir=/usr/local/mariadb/columnstore/mysql/db --plugin-dir=/usr/local/mariadb/columnstore/mysql/lib/plugin --user=mysql --log-error=$LOG_PREFIX/mysqld_err.log --pid-file=/usr/local/mariadb/columnstore/mysql/db/$(hostname).pid --socket=/usr/local/mariadb/columnstore/mysql/lib/mysql/mysql.sock --port=3306 > $LOG_PREFIX/mysqld.log &
else
    #/usr/sbin/mysqld --defaults-extra-file=/etc/my.cnf.d/columnstore.cnf --user=mysql --log-error=$LOG_PREFIX/mysqld_err.log --port=3306 > $LOG_PREFIX/mysqld.log &
    /usr/sbin/mysqld --user=mysql --log-error=$LOG_PREFIX/mysqld_err.log --port=3306 > $LOG_PREFIX/mysqld.log &
fi
sleep 1

exit 0
