#!/bin/bash

# This script gracefully stops MCS when it was compiles
# with SKIP_OAM_INIT=1

PROGS='workernode controllernode PrimProc ExeMgr DMLProc DDLProc mysqld WriteEngineServer'

MINOR=$1

if [ $MINOR -eq 4 ]; then
    MCS_INSTALL_DIR=/usr
else
    MCS_INSTALL_DIR=/usr/local/mariadb/columnstore
fi

$MCS_INSTALL_DIR/bin/save_brm

echo Sending SIGTERM
kill $(pidof $PROGS) > /dev/null
sleep 3
echo Sending SIGKILL
kill -9 $(pidof $PROGS) > /dev/null

echo Clearing SHM
$MCS_INSTALL_DIR/bin/clearShm

exit 0
