version: "3"
services:
  dev:
    image: ubuntu:focal
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
        - DISPLAY=:0
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - gitlocal:/gitlocal
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint:
      - /scripts/idle.sh 
  dev1:
    image: ubuntu:22.04
    privileged: true
    cap_add:
        - SYS_PTRACE
    ports:
        - 3308:3306
    environment:
        - USER=root
        - DISPLAY=:0
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint:
      - /scripts/idle.sh 
  dev2:
    image: ubuntu:22.04
    privileged: true
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
        - DISPLAY=:0
    volumes:
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint:
      - /scripts/idle.sh 
    ports:
#      - 3307:3306
#      - 8443:443
      - 8081:80
#      - 8082:8080
#      - 2560:2560
  dev3:
    image: coldev-ubuntu22
    privileged: true
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
        - DISPLAY=:0
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint:
      - systemd
  compiler:
    image: jr/colcomp
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  dev4:
    image: drrtuy/coldev-centos
#    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      #- /run/media/drrtuy/9756e9a5-f0db-460a-92b8-d07c119d23de:/usr/local/mariadb:rw # sda2
    entrypoint:
      - /scripts/idle.sh
  dev5:
    image: drrtuy/coldev-u16
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      #- dblocal4:/usr/local/mariadb
    entrypoint:
      - /scripts/idle.sh
  dev6:
    image: drrtuy/coldev-deb9
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh
  dev7:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  jdk:
    image: openjdk
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
     - /scripts/idle.sh 
volumes:
    gitlocal:    
    gitlocal1:    
    #dblocal:
    #dblocal1:
    #dblocal2:
    #dblocal3:
    #dblocal4:
    pm1:
    pm2:
    um1:
            #s1:
